/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CountyAdmin;

import Business.County.County;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ShippingOrderWR;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vedar
 */
public class CountyAdminAssignOrderJPanel extends javax.swing.JPanel {

    private UserAccount userAccount;
    private County county;
    
    /**
     * Creates new form CountyAdminAssignOrderJPanel
     */
    
    public CountyAdminAssignOrderJPanel(UserAccount userAccount,County county) {
        initComponents();
        
        this.userAccount = userAccount;
        this.county = county;
        
        populateOrderTable();
        populateDeliveryPicker();
        
    }

    private void populateDeliveryPicker(){
        shippingPartnerPicker.removeAllItems();
        
        String role = "Shipping Manager";
        
        for (UserAccount ua: county.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole().toString().equals(role)) {
                shippingPartnerPicker.addItem(ua);
            }
        }
    }
    
    
    private void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel)tblOrders.getModel();
        model.setRowCount(0);
        
        ArrayList<WorkRequest> workReq = county.getWorkQueue().getWorkRequestListArray();
        for(int i=workReq.size()-1; i>=0; i--){
            
            ShippingOrderWR lt = (ShippingOrderWR)workReq.get(i);
            Order order = lt.getOrders();
                Object[] row = new Object[5];
                row[0] = lt;
                row[1] = order.getId();
                row[4] = lt.getStatus();
                row[3] = order.getPrice();
                row[2] = order.getQuantity();
                model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        shippingPartnerPicker = new javax.swing.JComboBox();
        btnAssign = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));
        jPanel14.setPreferredSize(new java.awt.Dimension(997, 800));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Assign Order");

        tblOrders.setBackground(new java.awt.Color(204, 204, 204));
        tblOrders.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Order ID", "Quantity", "Price", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        btnAccept.setBackground(new java.awt.Color(204, 204, 204));
        btnAccept.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(204, 204, 204));
        btnReject.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Assign Shipping Partner");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setIconTextGap(0);

        lblName1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblName1.setText("Select Shipping Partner:");

        shippingPartnerPicker.setFont(new java.awt.Font("Devanagari MT", 0, 13)); // NOI18N
        shippingPartnerPicker.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        shippingPartnerPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingPartnerPickerActionPerformed(evt);
            }
        });

        btnAssign.setBackground(new java.awt.Color(204, 204, 204));
        btnAssign.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnAssign.setText("Assign Shipping Partner");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(589, 589, 589))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName1)
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addComponent(shippingPartnerPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnAssign))))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(283, 283, 283))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnAccept))
                .addGap(63, 63, 63)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shippingPartnerPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssign))
                .addGap(270, 270, 270))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1289, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this,"Please select a row to accept","Warring",JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest) tblOrders.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Order placed")){
            request.setStatus("Accepted");
            JOptionPane.showMessageDialog(this, "Order accepted successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Request cannnot be accepted/rejected","Warring",JOptionPane.WARNING_MESSAGE);
        }
        populateOrderTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed

        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to reject","Warrring",JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest) tblOrders.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Order placed")){
            request.setStatus("Rejected");
            JOptionPane.showMessageDialog(this, "Order rejected successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showConfirmDialog(this,"Requesr cannot be accepted/rejected","Warring",JOptionPane.WARNING_MESSAGE);
        }
        populateOrderTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblOrders.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to assing","Warring",JOptionPane.WARNING_MESSAGE);
            return;
        }

        ShippingOrderWR request = (ShippingOrderWR) tblOrders.getValueAt(selectedRow, 0);
        if (request.getStatus().equals("Accepted")) {
            UserAccount ua1 = (UserAccount)shippingPartnerPicker.getSelectedItem();
            request.setReceiver(ua1);
            request.setStatus("On the way");
            populateOrderTable();
            JOptionPane.showMessageDialog(this, "Order assigned successfully","Success",JOptionPane.INFORMATION_MESSAGE);

        } else{
            if(request.getStatus().equals("Sent") || request.getStatus().equals("Order placed")) {
                JOptionPane.showMessageDialog(this, "Please accept this request to assing","Warring",JOptionPane.WARNING_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Request cannot be assigned","Warring",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void shippingPartnerPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingPartnerPickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shippingPartnerPickerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox shippingPartnerPicker;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
